# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm6375-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),sm6375-common)

endif
